name: .NET Core Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    # Add a step for each solution file
    - name: Restore dependencies for KafkaProducer
      run: dotnet restore KafkaProducer/KafkaProducer.sln

    - name: Restore dependencies for KafkaConsumer
      run: dotnet restore KafkaConsumer/KafkaConsumer.sln

    # Add a build step for each solution file
    - name: Build KafkaProducer
      run: dotnet build KafkaProducer/KafkaProducer.sln --no-restore

    - name: Build KafkaConsumer
      run: dotnet build KafkaConsumer/KafkaConsumer.sln --no-restore

    # Add a test step for each test project
    - name: Test KafkaProducer
      run: dotnet test KafkaProducer.Tests/KafkaProducer.Tests.csproj --no-build --verbosity normal

    - name: Test KafkaConsumer
      run: dotnet test KafkaConsumer.Tests/KafkaConsumer.Tests.csproj --no-build --verbosity normal
